name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    name: test by gostor/gotgt
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: test
        run: sudo go test -v ./...
      - name: Dump docker logs on failure
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v1
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ always() }}

  test-by-openiscsi:
    name: test by real open-iscsi
    runs-on: ubuntu-latest
    steps:
      - name: setup kernel module
        run: |
          sudo modprobe target_core_mod
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: test
        run: sudo go test -tags=host -v ./...